# Generated by Django 3.1.3 on 2021-02-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20210215_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='portfolio_site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
