version: '3'
services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE='project_allocation'
      - MYSQL_USER='root'
      - MYSQL_PASSWORD='thisisdatabase'
      - MYSQL_ROOT_PASSWORD=''
#    volumes:
#      - /tmp/app/mysqld:/var/run/mysqld
#      - ./db:/var/lib/mysql
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

