# Generated by Django 3.1.3 on 2021-02-10 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID_no', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=300)),
                ('project_slug', models.SlugField(allow_unicode=True, unique=True)),
                ('session', models.CharField(max_length=9)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_projects', to='department.department')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_project', to='student.student')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('student', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ProjectChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3')])),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_project_choices', to='project.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='student.student')),
            ],
            options={
                'unique_together': {('project', 'student')},
            },
        ),
    ]
