# Generated by Django 3.1.3 on 2021-02-14 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(through='project.ProjectChoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectchoices',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectchoices',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
        migrations.RemoveField(
            model_name='project',
            name='student_ID_no',
        ),
    ]
