# Generated by Django 3.1.3 on 2021-02-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210221_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='can_be_taken_by',
            field=models.IntegerField(default=5),
        ),
    ]
