# Generated by Django 3.1.3 on 2021-02-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_can_be_taken_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='taken',
            field=models.IntegerField(default=0),
        ),
    ]
