# Generated by Django 3.1.3 on 2021-02-26 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lab',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='software_required',
            field=models.TextField(default=''),
        ),
    ]
