# Generated by Django 3.1.3 on 2021-02-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210227_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lab',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='software_required',
            field=models.TextField(),
        ),
    ]
