# Generated by Django 3.1.3 on 2021-02-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_project',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='assigned_project_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
