# Generated by Django 3.1.3 on 2021-02-24 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
        ('student', '0003_auto_20210222_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='supervisor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to='teacher.teacher'),
            preserve_default=False,
        ),
    ]
