# Generated by Django 3.1.3 on 2021-02-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210212_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='established_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
